/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Define  Logic GPIO PIN ---------------------
#define GPIO_PIN_SET 	1
#define GPIO_PIN_RESET 	0
#define GPIO_PIN_LOW	0
#define GPIO_PIN_HIGH	1

//define GPIO PIN ------
#define LED_GPIO_PORT	GPIOA
#define LED_GPIO_PIN	GPIP_Pin_5
#define LED_PIN5	5
#define LEDControl_SetClock		RCC_AHB1Periph_GPIOA

#define BUTTON_GPIO_PORT	GPIOC
#define BUTTON_GPIO_PIN		GPIO_Pin_13
#define BUTTON_PIN13		13
#define BUTTONControl_SetClock 	RCC_AHB1Periph_GPIOC

static
void Led_Init(void)
{

	//0eclare type variable GPIO Struct-
	GPIO_InitTypeDef GPIO_InitStructure;

	//Enable Clock GPTOA--
	RCC_AHB1PeriphClockCmd(LEDControl_SetClock, ENABLE);


	//Choose Pin Led-' -
	GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN;

	//Choose Pin Led as Out-
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;

	//Choose Speed Pin-
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	//Select type-' -
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

	//Select status
	GPIO_InitStructure.GPIO_PuPd = GPTO PuPd_DOWN ;

	//The function initializes all of the above values--
	GPIO_Init(LED_GPIO_PORT, &GPIO_InitStructure);

}

//Chan PC13 dieu khien button *****

static
void Button_Init(void)
{
	//0eclare type variable GPIO Struc-
	GPIO_InitTypeDef GPIO_InitStructure ;

	//Enable Clock GPI0C--
	RCC_AHB1PeriphClockCmd(BUTTONControl_SetClock, ENABLE);

	//Choose Pin BUTTON--
	GPIO_InitStructure.GPIO_Pin = BUTTON_GPIO_PIN;

	//Choose Pin Led as Input--
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;

	//Choose Speed Pin-
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	//Select status -
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;

	//The function initializes a11 of the above values
	GPIO_Init(BUTTON_GPIO_PORT, &GP10_InitStructure);
}



int main(void)
{
    /* Loop forever */
	for(;;);
}
